[build]
  command = "npm run build"
  publish = "dist"

# Handle Single Page Application (SPA) routing
# Proxy API requests to the Backend (MUST COME FIRST)
[[redirects]]
  from = "/api/*"
  to = "https://yt-notes-uyy0.onrender.com/api/:splat"
  status = 200
  force = true

# Handle Single Page Application (SPA) routing (Fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
